### ISSUE TITLE
Remove Trapdoor and Servo, Extend Silo length

### ISSUE THREAD

**Issue by ltchin** [skrub-wreckers/hardware#20]
Had a late night chat. Given that the robot appears to be dragging cubes along fine behind it, it looks like we don't need to have the trapdoor and servo combination. This will allow us to move the silo in even more as well. We'll extend the silo walls down to help drag blocks along.

I want to make sure that this is ok with the rest of the team:
@eric-wieser 
@johnzzhang 
@reilleya

**Comment by KevinMorrow** [comment]
Completed.
