### ISSUE TITLE
Make our hinges look like this

### ISSUE THREAD

**Issue by reilleya** [skrub-wreckers/hardware#22]
![20160120_193214](https://cloud.githubusercontent.com/assets/9787344/12468298/410405d6-bfb0-11e5-94c6-037ad88b9515.jpg)
![20160120_193218](https://cloud.githubusercontent.com/assets/9787344/12468299/4105e694-bfb0-11e5-8c21-16f5805e3d65.jpg)

**Comment by ltchin** [comment]
For clarification, this is the Staffbot from last year, so we know these work

**Comment by eric-wieser** [comment]
This has been done
